new key for org.apache.tomcat[.embed]
s4u/pgp-keys-map pull request #194
Opened 2021-07-13 20:48 UTC by aoindustries

The new signature is seen on Tomcat 7 builds and resolves to
"Violeta Georgieva Georgieva (CODE SIGNING KEY) <violetagg@apache.org>".

2021-07-13 20:55 UTC, aoindustries commented
Note: This signature is also listed at https://people.apache.org/keys/group/tomcat.asc

2021-07-13 21:24 UTC, slawekjaranowski requested changes

2021-07-13 21:24 UTC, slawekjaranowski commented on resources/pgp-keys-map.list
>                                    0xA9C5DF4D22E99998D9875A5110C01C5A2F6059E7
Maybe better and easier to maintain will be have one group with subgroup, like:
```
org.apache.tomcat.* = ....
```
we have the same keys

2021-07-13 23:32 UTC, aoindustries commented
Rebased and combined to a single rule.

2021-07-14 05:01 UTC, slawekjaranowski approved these changes

2021-07-14 05:01 UTC, merged