Add keys for dependencies of Dropwizard
s4u/pgp-keys-map pull request #480
Opened 2021-12-28 10:46 UTC by rhowe

These are the keys (or lack thereof) for the current dependencies of the
Dropwizard project.

I haven't verified their authenticity. Caveat emptor.

2021-12-28 10:47 UTC, rhowe commented
FYI @joschi & @jplock

2021-12-28 14:47 UTC, slawekjaranowski requested changes
Very thanks for this PR. 

Please also add some examples of artifacts to test pom, when version will be upgraded we have sure that keys is still correct.

You can add to `pgp-keys-map-test1/pom.xml` or create separate module if you wish add more dropwizard artifacts.

2021-12-28 14:47 UTC, slawekjaranowski commented on resources/pgp-keys-map.list
> +
The same key, please use group `com.github.docker-java = ....`

2021-12-28 14:47 UTC, slawekjaranowski commented on resources/pgp-keys-map.list
> +com.rabbitmq:amqp-client        = 0x0A9AF2115F4687BD29803A206B73A36E6026DFCA
use group `com.rabbitmq=...`

2021-12-28 14:47 UTC, slawekjaranowski commented on resources/pgp-keys-map.list
> +org.awaitility:awaitility       = 0x07E20F0103D9DFC697C490D0368557390486F2C5
group `org.awaitility=...`

2021-12-28 14:47 UTC, slawekjaranowski commented on resources/pgp-keys-map.list
> +                                  0x019082BC00E0324E2AEF4CF00D3B328562A119A7
group `org.openjdk.jmh=...`

2021-12-28 14:47 UTC, slawekjaranowski commented on resources/pgp-keys-map.list
> +
group, the same key `org.testcontainers=...`

2021-12-28 16:23 UTC, rhowe commented
> Very thanks for this PR.
> 
> Please also add some examples of artifacts to test pom, when version will be upgraded we have sure that keys is still correct.
> 
> You can add to `pgp-keys-map-test1/pom.xml` or create separate module if you wish add more dropwizard artifacts.

Thanks. I've added entries for everything, except the google protobuf key is for an older version of the lib than is in the test pom, so I left that version as-is.

2021-12-28 17:00 UTC, slawekjaranowski commented
@rhowe please fix build ...

2021-12-28 17:44 UTC, slawekjaranowski commented
You can use `org.glassfish.jersey.*` the same key is used.

I don't see any dependency for `io.dropwizard...`

Maybe  we can use also `io.dropwizard.*` for keys

2021-12-29 08:23 UTC, slawekjaranowski approved these changes

2021-12-29 08:24 UTC, merged